pipeline:
  build:
    image: docker:rc-git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - docker version
      - docker image build -f Dockerfile . -t gitea.treehouse.systems/treehouse/mastodon:latest

  push:
    image: docker:rc-git
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    commands:
      - echo $REGISTRY_SECRET | docker login -u ariadne --password-stdin gitea.treehouse.systems
      - docker image push --all-tags gitea.treehouse.systems/treehouse/mastodon
    when:
      event: [push, tag]
      branch: main
    secrets: [REGISTRY_SECRET]
